services:
  bot:
    build: .
   # image: ghcr.io/okiscape/cobaltposting-tgbot:latest
    container_name: cobaltposting-tgbot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./utils:/app/utils
